// Central registry of API error codes.
// The frontend maps each code to a localized (Spanish) message — never
// compare against the English `message` field, it can change wording
// without notice. This file is the single source of truth for codes.

module.exports = {
    // Auth
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
    DOCUMENT_ALREADY_REGISTERED: 'DOCUMENT_ALREADY_REGISTERED',
    ROLE_NOT_CONFIGURED: 'ROLE_NOT_CONFIGURED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    NOT_ADMIN_ACCOUNT: 'NOT_ADMIN_ACCOUNT',
    NO_TOKEN: 'NO_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
    RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',

    // Users / profile
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
    PASSWORD_UNCHANGED: 'PASSWORD_UNCHANGED',
    CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
    PRIMARY_ADMIN_PROTECTED: 'PRIMARY_ADMIN_PROTECTED',
    MIN_ONE_ADMIN_REQUIRED: 'MIN_ONE_ADMIN_REQUIRED',
    INVALID_ROLE: 'INVALID_ROLE',

    // Vehicles
    VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
    PLATE_ALREADY_REGISTERED: 'PLATE_ALREADY_REGISTERED',
    VEHICLE_HAS_ACTIVE_RESERVATION: 'VEHICLE_HAS_ACTIVE_RESERVATION',
    INVALID_PLATE_FORMAT: 'INVALID_PLATE_FORMAT',

    // Zones
    ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
    ZONE_NAME_TAKEN: 'ZONE_NAME_TAKEN',
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
    NEGATIVE_VALUE: 'NEGATIVE_VALUE',
    CAPACITY_BELOW_IN_USE: 'CAPACITY_BELOW_IN_USE',
    INSUFFICIENT_AVAILABLE_SPOTS: 'INSUFFICIENT_AVAILABLE_SPOTS',
    ZONE_INACTIVE: 'ZONE_INACTIVE',

    // Reservations
    START_TIME_IN_PAST: 'START_TIME_IN_PAST',
    END_BEFORE_START: 'END_BEFORE_START',
    NO_SPOTS_AVAILABLE: 'NO_SPOTS_AVAILABLE',
    RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
    RESERVATION_ALREADY_STARTED: 'RESERVATION_ALREADY_STARTED',
    RESERVATION_NOT_CANCELLABLE: 'RESERVATION_NOT_CANCELLABLE',

    // Payments
    INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
    CARD_DIGITS_REQUIRED: 'CARD_DIGITS_REQUIRED',
    RESERVATION_NOT_OWNED: 'RESERVATION_NOT_OWNED',
    RESERVATION_NOT_PENDING: 'RESERVATION_NOT_PENDING',
    PAYMENT_ALREADY_EXISTS: 'PAYMENT_ALREADY_EXISTS',
    PAYMENT_DECLINED: 'PAYMENT_DECLINED',

    // Generic
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
};